# Generated by Django 6.0.2 on 2026-03-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_by', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Transport', 'Transport'), ('Rent', 'Rent'), ('Wages', 'Wages'), ('Electricity', 'Electricity'), ('Airtime/Data', 'Airtime/Data'), ('Maintenance', 'Maintenance'), ('Miscellaneous', 'Miscellaneous')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
